### ISSUE TITLE
No module named 'comfyui_dynamicprompts'

### ISSUE THREAD

**Issue by AhmedGit** [adieyal/comfyui-dynamicprompts#1]
Not working.

ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts\__init__.py", line 1, in <module>
    from comfy_dynamicprompts.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'comfy_dynamicprompts'

**Comment by adieyal** [comment]
Could you give it another go and let me know if it works?

**Comment by AhmedGit** [comment]
it's installed correctly now, but on the output level, I don't think it works.
I have this wildcard named "__children_animals_minimal__", in the webui it generates the image grid attached.
but for the ComfyUI it generated strange images "three of them attached" as if it takes the file name as prompt, not its content.

This is the list included in the wild card:
fox
cat
squirrel
frog
duck
sheep
owl
rat
rabbit
crocodile

![webui](https://github.com/adieyal/comfyui-dynamicprompts/assets/7932193/6826cf6f-0d36-43b0-8a22-5d5301987e8b)

![ComfyUI_00036_](https://github.com/adieyal/comfyui-dynamicprompts/assets/7932193/1e16a7c2-4a69-4818-a8ef-79182dc46980)
![ComfyUI_00031_](https://github.com/adieyal/comfyui-dynamicprompts/assets/7932193/f44f706b-331e-41dc-9119-05990a41fac6)
![ComfyUI_00035_](https://github.com/adieyal/comfyui-dynamicprompts/assets/7932193/7dc241cf-7df0-452a-9d96-ebfca1281f24)

**Comment by adieyal** [comment]
Have a look in the console to see what the prompt is. Where is your wildcard folder? Perhaps it can't find it.

**Comment by AhmedGit** [comment]
I have used it where wildcards folder is in "ComfyUI/wildcards" or "ComfyUI/custom_nodes/comfyui-dynamicprompts/wildcards", non of them worked.
I also removed nested folders and used the wildcard file directly in the wildcard folder root, and didn't work either.

**Comment by adieyal** [comment]
Are you getting any useful output in the console?

**Comment by AhmedGit** [comment]
This is the wildcard I use, __testList__ containing these values (dog, cat, owl)

Console
No values found for wildcard testList
Prompt: __testList__

**Comment by AhmedGit** [comment]
Should I install any other wildcard custom nodes with it to work like "lordgasmic wildcards" custom node, or "lilly1987 simple wildcard for ComfyUI"?

**Comment by adieyal** [comment]
No, it should just work. To test, I did the following
1. `mkdir ComfyUI/wildcards`
2. Then I copied `children_animals_minimal.txt` into the wildcards folder
3. Finally I used a RandomPrompts node with this prompt `{red|green|blue} __children_animals_minimal__`

see the attached workflow. Can you try those exact steps and let me know if it still doesn't work?
![ComfyUI_00002_](https://github.com/adieyal/comfyui-dynamicprompts/assets/420786/c8974ff5-2f4e-4b8d-8661-5114160ca2d2)

[workflow.zip](https://github.com/adieyal/comfyui-dynamicprompts/files/12236890/workflow.zip)

**Comment by AhmedGit** [comment]
tried it, and this is what I get:

Console: 
got prompt
Prompt: green __children_animals_minimal__

image:
![ComfyUI_00079_](https://github.com/adieyal/comfyui-dynamicprompts/assets/7932193/31d6c607-862b-41cd-ac5b-07344d3ea948)

**Comment by adieyal** [comment]
looks like you're missing a double underscore in your prompt, it should be
`{red|green|blue} __children_animals_minimal__`

but I think you're using:

`{red|green|blue} _children_animals_minimal_`

**Comment by AhmedGit** [comment]
![Screenshot 2023-08-02 101303](https://github.com/adieyal/comfyui-dynamicprompts/assets/7932193/638f3749-2fd0-4da5-a46e-8a9498c7f41d)

**Comment by adieyal** [comment]
can you show me the contents of `ComfyUI/wildcards`

**Comment by AhmedGit** [comment]
[testList.txt](https://github.com/adieyal/comfyui-dynamicprompts/files/12237186/testList.txt)
![folder](https://github.com/adieyal/comfyui-dynamicprompts/assets/7932193/3d6ad52e-ae9c-48df-8aa7-8cd7ed85e244)
[children_animals_minimal.txt](https://github.com/adieyal/comfyui-dynamicprompts/files/12237187/children_animals_minimal.txt)

**Comment by adieyal** [comment]
I just had a look at your original issue:
```
ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts_init_.py", line 1, in
from comfy_dynamicprompts.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'comfy_dynamicprompts'
```

It looks like you have two ComfyUI directories. The wildcards directory should be parallel to custom_nodes or inside the extension's directory

i.e.
```
ComfyUI/
├─ wildcards # (option 1)
├─ custom_nodes/
│  ├─ comfui_dynamicprompts/
│  │  ├─ wildcards # (option 2)
```

Is that perhaps the problem?

**Comment by AhmedGit** [comment]
I have tried both options.
Option 1 doesn't give this error "No values found for wildcard", but doesn't list the values in the file.
Option 2 gives the above error in the console.

So, the current configuration is that Im using option 1 with wildcards folder on the same level as custom_nodes folder.

**Comment by adieyal** [comment]
To help me debug, could you please download this file and change the extension to `.py` then copy it over `comfy_dynamicprompts/nodes/sampler.py`

Generate your prompt again and then paste the output you see in the console. 

[sampler.txt](https://github.com/adieyal/comfyui-dynamicprompts/files/12237495/sampler.txt)

**Comment by AhmedGit** [comment]
Also  please add the option to refresh the wildcards folder, as it doesnot detect newly added files on the fly. I need to restart ComfyUI to read new files added. 

thanks.

**Comment by adieyal** [comment]
Thanks for figuring that out. I'll look into why that's happening, perhaps simply search in every directory starting with the root until I find a wildcards folder.

**Comment by AhmedGit** [comment]
Great efforts.
Best wishes.

**Comment by adieyal** [comment]
Closing this issue in favour of #8.
