### ISSUE TITLE
List errors with CLIPTextEncodeSDXL when using Portable ComfyUI

### ISSUE THREAD

**Issue by run-Fyre** [adieyal/comfyui-dynamicprompts#15]
Currently trying out using SDXL and have been using a workflow provided by another user at:
https://civitai.com/models/133420/make-good-pic-xl

However, have been running into issues due using strings for lists indexing instead of indices or slices

When running the prompt (as shown in the civitai link)
I am met with: 

> Error occurred when executing CLIPTextEncodeSDXL:
> 
>  list indices must be integers or slices, not str
>
> File "\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_clip_sdxl.py", line 43, in encode
> tokens["l"] = clip.tokenize(text_l)["l"]

I'm a little new to Python, so while I understand the issue is to do with list categorisation, I haven't quite worked out my steps to fix just yet.

Any help would be appreciated

**Comment by adieyal** [comment]
It's been a while since you posted, I hope you solved your problem. I'm not sure it is relevant to the dynamicprompts extension though.
