### ISSUE TITLE
dynamic prompts doesn't update its list of wild cards unless the server is restarted

### ISSUE THREAD

**Issue by bobpuffer1** [adieyal/comfyui-dynamicprompts#19]
ran into this one today. added a bunch of hair colors to the hair color wild cards. couldn't get random prompts to pick them up until I restarted the server

**Comment by adieyal** [comment]
Wildcards are cached for performance reasons - I'll give some thought as to the best way to trigger a cache invalidation.

**Comment by adieyal** [comment]
this is actually a duplicate of this issue: https://github.com/adieyal/comfyui-dynamicprompts/issues/4
