### ISSUE TITLE
Unable to enter prompt in Random Prompt node

### ISSUE THREAD

**Issue by 2x-y** [adieyal/comfyui-dynamicprompts#2]
If I try the random.json workflow the prompt box has no way to enter text but has a "text" endpoint that I can't attach to anything.
![image](https://github.com/adieyal/comfyui-dynamicprompts/assets/113105609/128bd2cd-4223-41c1-a3c1-4a6ef0cd9760)

**Comment by 2x-y** [comment]
I installed via the ComfyUI Manager extension and I didn't spot the instruction to copy the dp.js file to the web extensions folder.

**Comment by adieyal** [comment]
I haven't looked if there is a standard way to install web extensions yet. I there isn't one then I will write an install script to copy it to the right place.
