### ISSUE TITLE
Unable to install application comfyui-dynamicprompts, please help!

### ISSUE THREAD

**Issue by hzeasy** [adieyal/comfyui-dynamicprompts#33]
Hello,anyone willing to help me please review the information provided. I can confirm that the system environment is normal because other applications can start normally, but dynamicprompts cannot be executed.The installation process should be correct.
![6dd22df84708f7eef0ed05a116c0441](https://github.com/adieyal/comfyui-dynamicprompts/assets/136664755/a4dffb5f-3a50-48f0-b61e-ce5b80f920e2)

![b3dd324e6f512fa41ff7e7b6dfdf03c](https://github.com/adieyal/comfyui-dynamicprompts/assets/136664755/613ce95b-e9e4-45c0-b805-6df754eec551)
![6cf63a918e3a898d90c8aa9175c37cf](https://github.com/adieyal/comfyui-dynamicprompts/assets/136664755/c28cb8be-b67f-470b-9467-94829467c0f2)

【Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts\nodes\__init__.py", line 1, in <module>
    from .combinatorial import DPCombinatorialGenerator
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts\nodes\combinatorial.py", line 3, in <module>
    from dynamicprompts.enums import SamplingMethod
ModuleNotFoundError: No module named 'dynamicprompts'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts module for custom nodes: No module named 'dynamicprompts'】
@adieyal

**Comment by moctw** [comment]
I also encountered such a situation, I found that comfyUI is running the python environment really necessary package caused by installing the corresponding dynamicprompts package to solve, you can try, I hope it can help you.

**Comment by hzeasy** [comment]
> I also encountered such a situation, I found that comfyUI is running the python environment really necessary package caused by installing the corresponding dynamicprompts package to solve, you can try, I hope it can help you.

Thank you, the problem has been solved after reinstalling the node and updating comfyui to the latest version. @moctw

**Comment by adieyal** [comment]
glad you solved your problem.
