### ISSUE TITLE
Can't connect dynamic prompts to anything

### ISSUE THREAD

**Issue by darkpixel** [adieyal/comfyui-dynamicprompts#39]
The readme shows various prompts being connected to CLIP Text Encode blocks:

![image](https://github.com/adieyal/comfyui-dynamicprompts/assets/158380/260be317-10fb-4563-bacb-e0151d8b6368)

On my install, they won't connect to anything.

![Screenshot from 2023-12-25 09-22-41](https://github.com/adieyal/comfyui-dynamicprompts/assets/158380/41b67261-65b2-4b22-815e-8e11f6362035)

I just made sure ComfyUI was up-to-date and I'm running the latest version of dynamicprompts, no errors in the console when loading.

**Comment by slavikfoxy** [comment]
<img width="123" alt="image" src="https://github.com/adieyal/comfyui-dynamicprompts/assets/20266330/bc3ada69-9246-4c64-8ec4-b12985b3ab9c">
<img width="1200" alt="[image" src="https://github.com/adieyal/comfyui-dynamicprompts/assets/20266330/85680dec-78b3-45ef-8212-966f50480306">

**Comment by darkpixel** [comment]
Thanks.  I guess I'm a noob at Comfy UI. ;)
