### ISSUE TITLE
Wildcards doesn't work with files 

### ISSUE THREAD

**Issue by linnkoln** [adieyal/comfyui-dynamicprompts#9]
![image](https://github.com/adieyal/comfyui-dynamicprompts/assets/60001135/0de2bf03-e3c6-4c96-9074-12a3c038e9be)
Tested dynamic promts with random and combinational nodes. Both nodes working with {} syntax, but ignored __ __ constructions

**Comment by linnkoln** [comment]
![image](https://github.com/adieyal/comfyui-dynamicprompts/assets/60001135/73dce9aa-a7eb-4af2-b4c9-3f8c3f309da2)

**Comment by adieyal** [comment]
I think this is a duplicate of #8
